name: "Setup Bun Environment"
description: "Setup Bun and install dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      run: bun install
      shell: bash
