name: Test

on:
  push:
    paths:
      - 'src/**/*.ts'
      - 'src/**/*.js'
      - 'app/**/*.ts'
      - 'app/**/*.js'
      - 'test/**/*.ts'
      - 'test/**/*.js'
      - 'package.json'
      - 'bun.lockb'
      - 'tsconfig*.json'
      - 'vitest.config.*'
      - '.github/workflows/test.yml'
      - '.github/actions/**'

# 重複実行を防ぐconcurrency設定
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      API_KEY: test-api-key-for-github-actions
      NODE_ENV: test
      PORT: 3000
      DEBUG: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun Environment
      uses: ./.github/actions/setup

    - name: Build project
      run: bun run build

    - name: Build app examples
      run: bun run build:app

    - name: Generate CLI
      run: bun run dev:regen

    - name: Run unit tests
      run: bun run test

    - name: Run integration tests
      run: bun run test:integration:only